kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: mysql-pass
  namespace: wp
  literals:
  - password="wordpress"
resources:
  - wp.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
